---
name: Our Travel Blog
title: Almost Nomads
---

sass:
  style: compact

baseurl:  "\"

email: geren216@gmail.com

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - .AppleDouble/